---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jvm"

- name: gather internal_xms_size
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "/usr/bin/grep" | tr '[:upper:]' '[:lower:]' | grep -Po '(?<=xms)[^ ]+'
  register: internal_xms_size
  ignore_errors: yes
  when: 'jboss_eap'

- name: set xms_size fact
  set_fact:
    xms_size: "{{internal_xms_size.stdout}}"
  ignore_errors: yes
  when: 'jboss_eap'

- name: gather internal_xmx_size
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "/usr/bin/grep" | tr '[:upper:]' '[:lower:]' | grep -Po '(?<=xmx)[^ ]+'
  register: internal_xmx_size
  ignore_errors: yes
  when: 'jboss_eap'

- name: set xmx_size fact
  set_fact:
    xmx_size: "{{internal_xmx_size.stdout}}"
  ignore_errors: yes
  when: 'jboss_eap'

- name: gather internal_command_line_jboss
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "/usr/bin/grep" | tr -d '\r' | tr -d '\n'
  register: internal_command_line_jboss
  ignore_errors: yes
  when: 'jboss_eap'

- name: set command_line_jboss fact
  set_fact:
    command_line_jboss: "{{internal_command_line_jboss.stdout}}"
  ignore_errors: yes
  when: 'jboss_eap'
