- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jboss_host_controller"
    applications: []
    hashes: []
    hashes_tmp: []

# Evitar path dos servers ('/opt/jboss/jboss-eap/hc/data/servers/my-server/content/89/5e6dd810ba6c4ae83be2c5bce744bfed43ef7b/content')
# /opt/jboss-eap-7.0/domain/data/content/3b/09a90d049153284fa2b16461f7b793c632b4c3/content

- name: Find all content using eap_home_candidates
  find:
   paths: "{{ eap_home_candidates }}"
   patterns: 'content'
   recurse: yes
   file_type: file
   depth: 8
  ignore_errors: yes
  register: content_files_list
  when: 'jboss_eap and host_controller'

- name: Debug content_files_list
  debug:
    msg: "var = {{ content_files_list.files }}"
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

- name: Set fact with all hashes
  set_fact:
    hashes_tmp: "{{ hashes_tmp + [ item.split('/')[-3] + item.split('/')[-2] ] }}"
  ignore_errors: yes
  when: 'jboss_eap and host_controller'
  with_items: "{{ content_files_list.files | map(attribute='path') | select('match', '.*/servers/.*') | unique | list }}"

- name: Debug hashes_tmp
  debug:
    msg: "var = {{ hashes_tmp }}"
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

- name: Increment facts for hashes found
  set_fact:
    hashes: "{{ hashes + [ item ] }}"
  ignore_errors: yes
  when: 'jboss_eap and host_controller and item != ""'
  with_items: "{{ hashes_tmp | unique | list }}"
  # with_items: "{{ content_files_list.files | map() | list }}"

- name: Debug hashes
  debug:
    msg: "var = {{ hashes }}"
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

# - name: Find dc-* files
#   delegate_to: localhost
#   ignore_errors: yes
#   find:
#     paths: ["/tmp"]
#     patterns: 'dc-*.txt'
#     file_type: file
#   register: search_dc

- name: Set fact with applications matched
  set_fact:
    applications: "{{ applications + [ hostvars['localhost']['apps'][item]['app'] ] }}"
  ignore_errors: yes
  when: 'jboss_eap and host_controller and hostvars["localhost"]["apps"][item]'
  with_items: "{{ hashes }}"

#  - name: Salva alguma coisa no /tmp se hash existe
#     shell: "echo existe > /tmp/{{ hostvars['localhost']['apps'][item]['app'] }}"
#     with_items: "{{ hashes }}"
#     when: "{{ hostvars['localhost']['apps'][item] }}"

# - name: Search application
#   shell: "grep {{ item }} /tmp/dc-*.txt | cut -d, -f1 | uniq"
#   ignore_errors: yes
#   delegate_to: localhost
#   register: application_found
#   when: 'jboss_eap and host_controller and search_dc.matched > 0'
#   with_items: "{{ hashes }}"
    
# - name: Increment facts for application found
#   set_fact:
#     applications: "{{ applications + [ item.stdout ] }}"
#   ignore_errors: yes
#   when: 'jboss_eap and host_controller and search_dc.matched > 0 and item.stdout != ""'
#   with_items: "{{ application_found.results }}"

- name: remove facts
  set_fact:
    hashes: []
    hashes_tmp: []
  when: 'jboss_eap and host_controller'
  ignore_errors: yes