- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jboss_host_controller"
    applications: []
    hashes: []

# Evitar path dos servers ('/opt/jboss/jboss-eap/hc/data/servers/sicve-internet-prd-node01-lx671/content/89/5e6dd810ba6c4ae83be2c5bce744bfed43ef7b/content')
# /opt/jboss-eap-7.0/domain/data/content/3b/09a90d049153284fa2b16461f7b793c632b4c3/content

- name: Find all content using eap_home_candidates
  find:
   paths: "{{ eap_home_candidates }}"
   patterns: 'content'
   recurse: yes
   file_type: file
   depth: 8
  ignore_errors: yes
  register: content_files_list
  when: 'jboss_eap and host_controller'

- name: Debug content_files_list
  debug:
    msg: "var = {{ content_files_list.files | map(attribute='path') | select('match', '.*/servers/.*') | unique | list }}"
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

- name: List all SHAs from host controller
  shell: "echo {{ item.split('/')[-3] + item.split('/')[-2] }}"
  register: all_shas_tmp
  ignore_errors: yes
  when: 'jboss_eap and host_controller'
  # with_items: "{{ content_files_list.files }}"
  with_items: "{{ content_files_list.files | map(attribute='path') | select('match', '.*/servers/.*') | unique | list }}"

# {{ files | map(attribute='path') |  select('match', '.*/opt/teste.*') | list }}

- name: Debug all_shas_tmp
  debug:
    msg: "var = {{ all_shas_tmp }}"
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

- name: Increment facts for hashes found
  set_fact:
    hashes: "{{ hashes + [ item.stdout ] }}"
  ignore_errors: yes
  when: 'jboss_eap and host_controller and item.stdout != ""'
  with_items: "{{ all_shas_tmp }}"
  # with_items: "{{ content_files_list.files | map() | list }}"

- name: Debug hashes
  debug:
    msg: "var = {{ hashes }}"
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

# all_shas_tmp.stdout_lines

- name: Find dc-* files
  delegate_to: localhost
  ignore_errors: yes
  find:
    paths: ["/tmp"]
    patterns: 'dc-*.txt'
    file_type: file
  register: search_dc

- name: Search application
  shell: "grep {{ item }} /tmp/dc-*.txt | cut -d, -f1 | uniq"
  ignore_errors: yes
  delegate_to: localhost
  register: application_found
  when: 'jboss_eap and host_controller and search_dc.matched > 0'
  with_items: "{{ hashes }}"
    
- name: Increment facts for application found
  set_fact:
    applications: "{{ applications + [ item.stdout ] }}"
  ignore_errors: yes
  when: 'jboss_eap and host_controller and search_dc.matched > 0 and item.stdout != ""'
  with_items: "{{ application_found.results }}"

- name: remove facts
  set_fact:
    hashes: []
  when: 'jboss_eap and host_controller'
  ignore_errors: yes

# - name: get jboss.domain.base.dir path
#   raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "/usr/bin/grep" | grep -Pio '(?<=jboss.domain.base.dir=)[^ ]+'
#   register: jboss_domain_base_dir_internal
#   ignore_errors: yes
#   when: 'jboss_eap and host_controller and (jboss_eap_running_paths | length) > 0'

# - name: get jboss.home.dir path
#   raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "/usr/bin/grep" | grep -Pio '(?<=jboss.home.dir=)[^ ]+'
#   register: jboss_home_dir_internal
#   ignore_errors: yes
#   when: 'jboss_eap and host_controller and jboss_domain_base_dir_internal.rc != 0 and (jboss_eap_running_paths | length) > 0'

# - name: List all SHAs from host controller using jboss_domain_base_dir
#   shell: "cd {{ jboss_domain_base_dir_internal.stdout | trim }}/domain/data/content && find . -mindepth 2 -type d | tr -d './'"
#   register: jboss_host_controller_sha1
#   ignore_errors: yes
#   when: 'jboss_eap and host_controller and jboss_domain_base_dir_internal.rc == 0 and (jboss_eap_running_paths | length) > 0'

# - name: List all SHAs from host controller using jboss.home.dir
#   shell: "cd {{ jboss_home_dir_internal.stdout | trim }}/domain/data/content && find . -mindepth 2 -type d | tr -d './'"
#   register: jboss_host_controller_sha1
#   ignore_errors: yes
#   when: 'jboss_eap and host_controller and jboss_domain_base_dir_internal.rc != 0 and (jboss_eap_running_paths | length) > 0'

