- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jboss_domain_controller"
    domain_files: []

- name: Find all domain.xml using eap_home_candidates
  find:
   paths: "{{ eap_home_candidates }}"
   patterns: 'domain.xml'
   recurse: yes
   file_type: file
   depth: 6
  ignore_errors: yes
  register: jboss_domain_xml_files_list
  when: 'jboss_eap and domain_controller'

- name: Debug domain.xml list file
  debug:
    msg: "var = {{ jboss_domain_xml_files_list }}"
  when: 'jboss_eap and domain_controller'
  ignore_errors: yes

- name: Build domain file list
  set_fact:
    domain_files: "{{ domain_files + [ item.path ] }}"
  with_items: "{{ jboss_domain_xml_files_list.files }}"
  ignore_errors: yes
  when: jboss_eap and domain_controller and jboss_domain_xml_files_list.matched > 0

- name: Obtem Hashes com base no domain.xml
  shell: "cat {{ item }} | grep sha1 | grep -o '\".*\"' | tr -d '\"' | while read -r hash; do cat {{ item }} | grep $hash -B3 | grep -o 'deployment name=\".*\" ' | grep -o '\".*\"' | tr -d '\"' | tr -d '\\\n' ; echo \",$hash\"; done"
  register: name_hash_var
  ignore_errors: yes
  when: 'jboss_eap and domain_controller'
  with_items: "{{ domain_files }}"

- name: Debug name_hash_var
  debug:
    msg: "var = {{ name_hash_var.results }}"
  when: 'jboss_eap and domain_controller'
  ignore_errors: yes

- name: Create empty fact for applications
  set_fact:
    apps_internal: []
  when: 'jboss_eap and domain_controller'
  ignore_errors: yes

- name: Generate array from string
  set_fact:
    apps_internal: "{{ apps_internal + item.stdout_lines }}"
  ignore_errors: yes
  when: 'jboss_eap and domain_controller and (name_hash_var.results  | length) > 0'
  with_items: "{{ name_hash_var.results }}"

- name: Debug super array
  debug:
    msg: "var = {{ apps_internal }}"
  when: 'jboss_eap and domain_controller'
  ignore_errors: yes

- name: Loop over SHAs
  shell: "grep {{ item.split(',')[1] }} /tmp/dc-{{inventory_hostname}}.txt || echo {{ item }} >> /tmp/dc-{{inventory_hostname}}.txt"
  ignore_errors: yes
  delegate_to: localhost
  when: 'jboss_eap and domain_controller'
  with_items: "{{ apps_internal }}"

- name: remove facts
  set_fact:
    apps_internal: []
    domain_files: []
  when: 'jboss_eap and domain_controller'
  ignore_errors: yes