---
- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jboss_info"

- name: Init vars
  set_fact:
    jboss_is_running: false
    standalone: false
    domain_controller: false
    host_controller: false
    domain_controller_host: ""
    discover_customization_version: 1.0.6
    jboss_legacy_version: false
    jboss_processes: ""

- name: check if jboss is running
  raw: ps aux | grep java | grep jboss | grep -v "grep"
  register: internal_jboss_is_running_process
  ignore_errors: yes
  when: 'jboss_eap'

- name: Set fact jboss is running
  set_fact:
    jboss_is_running: true
  when: (jboss_eap_running_paths | length > 0) and (internal_jboss_is_running_process is defined) and (internal_jboss_is_running_process.rc == 0)

- name: gather jboss.processes
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep"
  register: internal_jboss_processes
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: set jboss_processes fact
  set_fact:
    jboss_processes: "{{ internal_jboss_processes.stdout | trim }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: Gather number of new EAP instances (EAP 6, EAP 7)
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | grep "\-D\[Server:" | wc -l
  register: internal_eap_number_instances
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: set number of EAP instances fact
  set_fact:
    eap_number_instances: "{{ internal_eap_number_instances.stdout | trim }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: Gather number of EAP process
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | wc -l
  register: internal_eap_number_process
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: set number of all EAP process fact
  set_fact:
    eap_number_process: "{{ internal_eap_number_process.stdout | trim }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: legacy version check process controller
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | grep "\-D\[Process Controller\]"
  register: internal_legacy_check_process_controller
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: legacy version check host controller
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | grep "\-D\[Host Controller\]"
  register: internal_legacy_check_host_controller
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: Set fact legacy version
  set_fact: 
    jboss_legacy_version: "{{ (internal_legacy_check_process_controller.rc != 0 or internal_legacy_check_process_controller.stdout == '') and (internal_legacy_check_host_controller.rc != 0 or internal_legacy_check_host_controller.stdout == '') }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: standalone check
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | grep "\-D\[Standalone\]"
  register: internal_standalone_check
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: set standalone check fact
  set_fact:
    standalone: "{{ internal_standalone_check.rc == 0 }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: set jboss domain controller initial score
  set_fact:
    jboss_host_controller_score: 0
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: check if this machine is the host controller using ps
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | grep -Pio '(?<=host-config=)[^ ]+' | grep -i slave
  register: internal_controller_check_ps # if internal_controller_check_ps.rc == 0 then it is host controller
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: check if this machine is the domain controller using management port
  raw: netstat -lnp | grep 9990 | grep java | grep -v grep
  register: internal_controller_check_port # if internal_controller_check_port.rc == 0 then it is domain controller
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: check if this machine is the host controller using master-address param
  raw: ps -auxwww | grep java | grep master-address | grep -v grep
  register: internal_controller_check_param # if internal_controller_check_param.rc == 0 then it is host controller
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: check if this machine is the host controller using port connection
  raw: netstat -an | grep ESTA | awk {'print $5'} | grep 9999 | grep -v grep
  register: internal_controller_port_connection # if internal_controller_port_connection.rc == 0 then it is host controller
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

# Computa o score se encontrando o master-address
- name: Compute jboss host controller score when internal_controller_check_param
  set_fact:
    jboss_host_controller_score: "{{ (jboss_host_controller_score | int) + 2 }}"
  ignore_errors: yes
  when: 'jboss_eap and internal_controller_check_param.rc == 0 and jboss_is_running'

# Computa o score do comando PS
- name: Compute jboss host controller score when internal_controller_check_ps
  set_fact:
    jboss_host_controller_score: "{{ (jboss_host_controller_score | int) + 1 }}"
  ignore_errors: yes
  when: 'jboss_eap and internal_controller_check_ps.rc == 0 and jboss_is_running'

# Computa o score se encontrando a management port
- name: Compute jboss domain controller score when internal_controller_check_port
  set_fact:
    jboss_host_controller_score: "{{ (jboss_host_controller_score | int) - 1 }}"
  ignore_errors: yes
  when: 'jboss_eap and internal_controller_check_port.rc == 0 and jboss_is_running'

# Computa o score se houver conexão de saída para o domain
- name: Compute jboss domain controller score when internal_controller_port_connection
  set_fact:
    jboss_host_controller_score: "{{ (jboss_host_controller_score | int) + 1 }}"
  ignore_errors: yes
  when: 'jboss_eap and internal_controller_port_connection.rc == 0 and jboss_is_running'

- name: set domain controller fact
  set_fact:
    domain_controller: "{{ (jboss_host_controller_score | int) < 2 and not jboss_legacy_version }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: get domain controller host
  raw: ps -A -o comm -o args e --columns 10000 | grep java | grep jboss | grep -v "grep" | grep -Pio '(?<=master.address=|master-address=)[^ ]+' | uniq
  register: internal_domain_controller_host
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'

- name: set domain controller host fact
  set_fact:
    domain_controller_host: "{{ internal_domain_controller_host.stdout | trim }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running and internal_domain_controller_host.rc == 0'

- name: set host controller fact
  set_fact:
    host_controller: "{{ (jboss_host_controller_score | int) >= 2 and internal_standalone_check.rc != 0 and not jboss_legacy_version }}"
  ignore_errors: yes
  when: 'jboss_eap and jboss_is_running'